variables:
  DOCKER_SNAPSHOT_REGISTRY: registry.axwaytest.net
  IMAGE: ${DOCKER_SNAPSHOT_REGISTRY}/jdavanne/mqtt-proxy:$CI_BUILD_REF
  NAME: mqtt-proxy

image: docker:latest
before_script:
- docker info

build:
  stage: build
  script:
  - docker build -t ${IMAGE}-build .
  - docker run --rm ${IMAGE}-build tar cz ${NAME} >${NAME}.tar.gz
  - docker build -t ${IMAGE} -f Dockerfile.small .
  - docker rmi ${IMAGE}-build
  #- docker push ${IMAGE}
  tags:
  - shared
